version: '3'

services:
  backend:
    container_name: "onyxya_dev"
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "3000:3000"
      - "5173:5173"
    #restart: no