version: '3.8'

services:
  dev:
    image: node:20.15-alpine3.20
    container_name: onyxya-dev
    user: node
    working_dir: /home/node
    # You can comment the 'command' row if you want to run npm install manually
    command: ["/bin/sh", "-c", "npm install && tail -f /dev/null"]
    volumes:
      - ./packages:/home/node/packages
      - ./package.json:/home/node/package.json
      # Add medias folder if needed
    tty: true
    stdin_open: true
    environment:
      - ONYXYA_API_PORT=3000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "3000:3000"
      - "5173:5173"
