version: '3.8'

services:
  dev:
    image: node:lts-alpine
    container_name: onyxya-dev
    user: node
    working_dir: /home/node
    volumes:
      - .:/home/node
    command: ./start-dev.sh
    ports:
      - "3000:3000"
      - "5173:5173"
