version: '3.8'

services:
  dev:
    image: node:20.14-alpine3.20
    container_name: onyxya-dev
    user: node
    working_dir: /home/node
    volumes:
      - .:/home/node
    tty: true
    stdin_open: true
    environment:
      - ONYXYA_API_PORT=3000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "3000:3000"
      - "5173:5173"
