version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    container_name: onyxya-prod-backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    container_name: onyxya-prod-frontend
    ports:
     - "80:80"
    depends_on:
     - backend
