# Version can be obsolet depending on your docker / docker compose version
version: '3.8'

services:
  dev:
    image: node:20.15-alpine3.20
    container_name: onyxya-dev
    #user: node # We need to be root, Can cause problems if used as node
    working_dir: /home/node
    # Comment one of the two lines according to the launch command you wish to use
    #command: ["/bin/sh", "-c", "mkdir -p /home/node/media/output && apk update && apk add --no-cache ffmpeg && npm install && tail -f /dev/null"]
    command: ["/bin/sh", "-c", "mkdir -p /home/node/media/output && apk update && apk add --no-cache ffmpeg"]
    volumes:
      - ./packages:/home/node/packages
      - ./package.json:/home/node/package.json
#      - your-music-path:/home/node/media/music
#      - your-movies-path:/home/node/media/movies
#      - your-series-path:/home/node/media/series
      # Add other medias folder if needed
#      - ./node_modules # uncomment if you want to use your own node_modules
    tty: true
    stdin_open: true
    environment:
      - ONYXYA_API_PORT=3000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      # Don't forget to change admin's credentials
      - ONYXYA_OWNER_USERNAME=admin
      - ONYXYA_OWNER_PASSWORD=changeme
    ports:
      - "3000:3000"
      - "5173:5173"
