FROM node:lts-alpine

WORKDIR /onyxya

COPY package.json /onyxya/package.json
COPY packages /onyxya/packages

RUN npm install

EXPOSE 3000
EXPOSE 5173

CMD npm -w packages/frontend run dev & npm -w packages/backend run start:dev