export const usernameMaxLength: number = 20;
export const usernameMinLength: number = 4;
export const passwordMinLength: number = 6;
export const passwordMaxLength: number = 20;
export const possiblesRoles: readonly string[] = ['admin', 'user'];
export const playlistNameMinLength = 2;
export const playlistNameMaxLength = 50;
export const playlistDescMinLength = 0;
export const playlistDescMaxLength = 255;
